// <auto-generated />
using FPS_TCG.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPS_TCG.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208133236_SupportDescription")]
    partial class SupportDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("DeckCard", b =>
                {
                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeckId", "CardId");

                    b.HasIndex("CardId");

                    b.ToTable("DeckCards", (string)null);
                });

            modelBuilder.Entity("FPS_TCG.Server.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Shield")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skill1Cost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skill1Damage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skill1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Skill2Cost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skill2Damage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skill2Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SupportCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportEffect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CardId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("FPS_TCG.Server.Models.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("DeckCard", b =>
                {
                    b.HasOne("FPS_TCG.Server.Models.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPS_TCG.Server.Models.Deck", null)
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
