// <auto-generated />
using FPS_TCG.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPS_TCG.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260111144259_Card2")]
    partial class Card2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("FPS_TCG.Server.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Skill1Cost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skill1Damage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skill1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Skill2Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skill2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("shield")
                        .HasColumnType("INTEGER");

                    b.Property<string>("skill2Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("supportCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("supportEffect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("FPS_TCG.Server.Models.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("FPS_TCG.Server.Models.Card", b =>
                {
                    b.HasOne("FPS_TCG.Server.Models.Deck", null)
                        .WithMany("Cards")
                        .HasForeignKey("DeckId");
                });

            modelBuilder.Entity("FPS_TCG.Server.Models.Deck", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
